### ISSUE TITLE
UIFlow

### ISSUE THREAD

**Issue by klebermagno** [FlorianPoot/M5StickCWatch#2]
Is possible use UIFlow to upload your project ?
UIFlow apparently work with only one python file.
Your project is very interesting

**Comment by FlorianPoot** [comment]
I think you can use M5Burner to upload my project. But you can not use UIFlow, because I used a firmware without it. Here is the firmware I used: https://github.com/m5stack/M5Stack_MicroPython/tree/StickC

And thank you, for being interested in my project, it's not completely finished but I will work on it in the next few days.

**Comment by FlorianPoot** [comment]
You can also, after burning MicroPython, upload the files with my tool AmpyGUI: https://github.com/FlorianPoot/AmpyGUI
